server:
  port: 8091

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5432/omega
  kafka:
    bootstrap-servers: localhost:9092

momiji:
  clients:
    bots:
      stub: true
      urls:
        - http://localhost:8093
    frontends:
      enabled: true
      stub: true
      urls:
        telegram: http://localhost:8094

logging:
  level:
    com.momiji.api: trace
    com.momiji.gateway.service: trace
    com.momiji.gateway.controller: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /openapi/gateway.yaml
