server:
  port: 8080

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5429/gateway

momiji:
  frontends:
    telegram:
      url: http://localhost:8090
  bots:
    - http://localhost:8081
