server:
  port: 8091

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5429/omega

momiji:
  clients:
    bots:
      stub: false
      urls:
        - http://localhost:8093
    frontends:
      enabled: true
      stub: false
      urls:
        telegram: http://localhost:8094

logging:
  level:
    com.momiji.api: trace
    com.momiji.gateway.service: trace
    com.momiji.gateway.controller: trace

cloud:
  aws:
    s3:
      endpoint: http://localhost:4566
