server:
  port: 8080

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5429/gateway

momiji:
  clients:
    bots:
      stub: true
      urls:
        - http://localhost:8081
    frontends:
      enabled: true
      stub: false
      urls:
        telegram: http://localhost:8090

logging:
  level:
    com.momiji.api: debug
