server:
  port: 8091

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5429/omega

momiji:
  clients:
    bots:
      stub: true
      urls:
        - http://localhost:8093
    frontends:
      enabled: true
      stub: true
      urls:
        telegram: http://localhost:8094

logging:
  level:
    com.momiji.api: trace
    com.momiji.gateway.service: trace
    com.momiji.gateway.controller: trace

s3:
  region: us-east-1
  host: localhost
  port: 9000
  path: /
  scheme: http
  access-key-id: accessKey1
  secret-access-key: verySecretKey1
