spring:
  application:
    name: messenger-gateway
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: true
logbook:
  format.style: http

logging:
  level:
    org.zalando.logbook: trace
