version: '3'

services:
  postgres:
    build:
      context: ./postgres-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase:
    image: liquibase/liquibase:4.19
    volumes:
      - "./changelog:/liquibase/changelog"
    command: >
      --url="jdbc:postgresql://postgres:5432/messages"
      --changeLogFile=/changelog/changelog-master.yaml
      --username=user
      --password=user
      update
#    entrypoint: "cat /changelog/changelog-master.yaml"
    depends_on:
      - postgres
