version: '3'

services:
  postgres:
    build:
      context: ./postgres-db
    ports:
      - "5429:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.19
    volumes:
      - "./changelog:/liquibase/changelog"
    command: >
      --url="jdbc:postgresql://postgres:5432/gateway"
      --changeLogFile=/changelog/changelog-master.yaml
      --username=nonroot
      --password=nonroot
      update
    depends_on:
      postgres:
        condition: service_healthy

  s3:
    image: scality/s3server:latest
